# Generated by Django 5.2 on 2025-05-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebo', '0003_inmemo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmemo',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
